# Use an official Node runtime as the parent image
FROM node:14

# Set the working directory in the container to /app
WORKDIR /app

# Copy package.json and package-lock.json to the container
COPY package*.json ./

# Install the React app dependencies inside the container
RUN npm install

# Copy the rest of the application to the container
COPY . .

# Specify the command to run on container start
CMD [ "npm", "start" ]
