# Use an official Node runtime as the parent image
FROM node:14

# Set the working directory in the container to /server
WORKDIR /server

# Copy package.json and package-lock.json to the container
COPY package*.json ./

# Install the server dependencies inside the container
RUN npm install

# Copy the rest of the server to the container
COPY . .

# Specify the port the server runs on
EXPOSE 5000

# Specify the command to run on container start
CMD [ "node", "server.js" ]



